#15 Structuredview
monogon-dev/intellij-cue pull request #63
Opened 2023-04-23 17:26 UTC by borissmidt

I have created a basic structured view and hopefully will find some time to add navigation and code completion.
Its a bit sad that nor VS code nor intellij have proper support for CUE limiting its adoption.

2023-04-23 17:32 UTC, borissmidt commented
example:
![image](https://user-images.githubusercontent.com/5995670/233855333-429f67f2-f9db-4b5a-a2f0-d685f45a9a61.png)
```cue
#Logging: {
	destination: string
	root_level:  "DEBUG" | "INFO" | "WARN" | "ERROR"
	loggers: [...#Logger]
	#Logger: {
			level: "DEBUG" | "INFO" | "WARN" | "ERROR"
			//	todo we could use a regex to check if it is valid.
			name: string
	}
}
```

2023-07-01 09:26 UTC, borissmidt commented
Could this pr be merged? Or would it be better to make a fork?

2023-07-01 09:28 UTC, jansorg commented
This pr deletes all (?) of the generated sources, but they must be kept. Could you revert this change, please?
After that I can have a look at the implementation.

2023-07-01 13:00 UTC, borissmidt commented
I've regenerated them and added the missing parser files.

2023-07-01 13:17 UTC, jansorg commented
_CueLexer and ellipsis.txt are still deleted, but shouldn't. Please make sure that no files are removed unless it's needed and that the PR is ready for review

2023-07-01 14:59 UTC, jansorg requested changes
First round of review. Once it's cleaned up, I'll take a closer look at the structure view. But at first glance it seems alright.

2023-07-01 14:59 UTC, jansorg commented on src/grammar/cue.bnf
> +methods = [getReferences]
seems to be unused, it won't generate a method on a `private` rule

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/psi/impl/CuePsiImplUtil.java
> +    static Logger logger = Logger.getInstance(CuePsiImplUtil.class);
unused field, please remove it

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/psi/impl/CuePsiImplUtil.java
> +//        logger.warn("getting representation for "+ field.getName());
please remove logger statements used for debugging

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/psi/impl/CuePsiImplUtil.java
> +    public static ItemPresentation getPresentation(CueField field) {
I prefer `@Nullable` and `@NotNull` annotations.
Please declare the return type as `@Nullable` and the paramter as `@NotNull`

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/psi/impl/CuePsiImplUtil.java
> +        var name = field.getLabelList().stream().map(PsiElement::getText).reduce((x,y) -> x + "." + y);
You could `return null` here if name is empty, because the presentation would have no presentable text in this case.

2023-07-01 14:59 UTC, jansorg commented on src/grammar/cue.bnf
> +Expression ::= UnaryExpr | UnificationBinaryExpr | BinaryExpr // fixme extra root?
Was `UnificationBinaryExpr` only introduced to be able to use it in structure view?
You could also expose left and right tokens of `BinaryExpr`.
Alternatively you could keep `UnificationBinaryExpr`, but make it `extend = BinaryExpr` and expose left and right tokens in `BinaryExpr` instead. This way `UnificationBinaryExpr` is just a subtype of `BinaryExpr`.

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CuePsiStructureViewFactory.java
> +import com.intellij.json.structureView.JsonStructureViewModel;
Please reformat this file and remove unused imports (this line is unused)

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureView.java
> + * Copyright (C) 22.04.23 - REstore NV
Please clarify what this copyright does.
Is this you or is this copied code? If yes, where does it come from?

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureView.java
> +        logger.info("handeling:" + psiFile);
remove logging

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureView.java
> +        withSuitableClasses(CueFile.class);
AFAIK this isn't complete, but it probably doesn't matter because it's (only?) used by a navbar extension based on structure view.

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureViewElement.java
> +/**
same as above

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureViewElement.java
> +public class CueStructureViewElement implements StructureViewTreeElement {
Most existing implementations in the SDK extend `PsiTreeElementBase`. Is there a reason not to use it?

2023-07-01 14:59 UTC, jansorg commented on src/main/java/dev/monogon/cue/lang/navigation/CueStructureViewElement.java
> +        // Using aggregator since we have binary op & where each one of them can be a CueStructLit which defines new fields
please reformat this file and remove warnings raised by IntelliJ

2023-07-01 14:59 UTC, jansorg commented on src/test/data/lang/cue/parser/fields_dynamic.txt
> +FILE(0,275)
Are these changes necessary for this? If not, please revert

2023-07-01 14:59 UTC, jansorg commented on src/test/data/lang/cue/parser/struct_attributes.txt
> +FILE(0,432)
Are these changes necessary for this? If not, please revert

2023-07-01 14:59 UTC, jansorg commented on src/test/data/lang/cue/parser/struct_closed.txt
> +FILE(0,458)
Are these changes necessary for this? If not, please revert

2023-07-01 14:59 UTC, jansorg commented on src/test/data/lang/cue/parser/struct_hidden.txt
> +FILE(0,644)
Are these changes necessary for this? If not, please revert

2023-07-01 14:59 UTC, jansorg commented on src/test/data/lang/cue/strucuted_view/Shorthand.cue
> + job: myTask: replicas: 2
Are these changes necessary for this? If not, please revert

2023-07-01 14:59 UTC, jansorg commented on src/test/java/dev/monogon/cue/lang/navigation/CueStructureViewElementTest.java
> + */
A test would be very useful. Let me know if you can't find how to make one.

2023-07-06 14:08 UTC, jansorg commented on src/test/java/dev/monogon/cue/lang/parser/CueParserTest.java
> +            doTest(true, !getTestName().toLowerCase().contains("error"));
The platform already supports a system property to automatically override the test data on disk:
```
systemProperties["idea.tests.overwrite.data"] = true
```
Please revert this change, I'll add a run configuration to `master` with sets the property

2023-07-06 14:14 UTC, jansorg requested changes
Thanks for the update! Only a few minor notes and then it should be good to go.
Could you please clarify the copyright statements  `Copyright (C) 23.04.23 - REstore NV` in the code? This `REstore NV` referring to yourself? I don't think the Cue plugin project has a guideline how to handle such copyright notes, I'll ask the company funding its development...

2023-07-06 14:14 UTC, jansorg commented on src/grammar/cue.bnf
> +UnificationBinaryExpr ::= Expression OP_UNIFICATION Expression  {
If you'd like to keep this, please make it `extend=BinaryExpr`. If you also move the `methods=` part to `BinaryExpr`, then the other code referencing left and right will work without any other changes.

2023-07-06 17:48 UTC, borissmidt commented
The copy right was just a setting which was still enabled in my Ide i turned it off now.

2023-07-07 09:53 UTC, merged

2023-07-07 10:07 UTC, borissmidt commented
:partying_face: